refactor: replace osutil with sysinfo
earthly/earthly pull request #1943
Opened 2022-06-18 19:35 UTC by Stitch-Zhang

2022-06-18 19:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/earthly/earthly?pullRequest=1943) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/earthly/earthly?pullRequest=1943) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/earthly/earthly?pullRequest=1943) it.</sub>

2022-06-22 18:03 UTC, alexcb commented
We can take a look at this PR @Stitch-Zhang if you sign the CLA and re-open it.

2022-06-27 18:24 UTC, alexcb requested changes
Thanks for switching out the library. Just a minor request, then I think we'll be good to merge it in.

2022-06-28 14:52 UTC, Stitch-Zhang commented on cmd/earthly/main.go
> +	showOSInfo := func() string {
ok

2022-06-28 17:49 UTC, alexcb approved these changes

2022-06-28 19:04 UTC, merged